#!/bin/bash

display_help() {
	echo "Usage: ntw-scan [options]"
	echo "Options:"
	echo "	--all		Get info about all hosts in the current subnet;"
	echo "	--target [ip]	Get info about open TCP ports;"
	echo "	--help		Display this help message."
}

display_all_ip() {
	subnet_ip=$( route | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}\s+([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $1}')	# getting current subnet ip
	subnet=$( ipcalc -n -b $subnet_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}')				# getting [ip]/[mask]

	echo "IP addresses and symbolic names of all hosts in the $subnet subnet:"
	nmap -sn "$subnet" | awk '/Nmap scan report for/{print $5}' | while read -r ip; do	# resolving list of active hosts
    		host=$(getent hosts "$ip" | awk '{print $2}')
    		if [$host -eq ""];								# checking if hostname is known
    		then
    			host="Unknown"
    		fi
    		echo "IP: $ip, Hostname: $host"							# displaying found addresses
	done
}

display_ports() {
	if [ $# -eq 0 ];
	then
		nmap localhost									# localhost port scan
	else
		nmap $1										# specified target port scan
	fi
}

case $1 in
	"" | --help)
		display_help
		;;
	--all)
		display_all_ip
		;;
	--target)
		display_ports $2
		;;
	*)
		echo "Invalid argument!"
		;;
esac
