#!/bin/bash

file_out=out
grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" $1 | sort | uniq -c | sort -gr > $file_out
{
read line
} < $file_out
echo -e "\e[31m1.\e[0m From which ip were the most requests? --> $line"

awk '{print $7}' $1 | sort | uniq -c | sort -gr > $file_out
{
read line
} < $file_out
echo -e "\e[31m2.\e[0m What is the most requested page? --> $line"

echo -e "\e[31m3.\e[0m How many requests were there from each ip?:"
awk '{print $1}' $1 | sort | uniq -c | sort -nr > $file_out
{
while read line; do echo $line; done
} < $file_out

echo -e "\e[31m4.\e[0m What non-existent pages were clients referred to?:"
awk '$9 == 302 {print $7}' $1 | grep -v "\"-\"" > $file_out
{
while read line; do echo $line; done
} < $file_out

echo -e "\e[31m6.\e[0m What search bots have accessed the site? (UA + IP):"
awk -F'-' '$4 ~ /bot|crawler|spider|googlebot|bingbot|yahoo|yandex/ {print $1,$4}' $1 | sort | uniq > $file_out
{
while read line; do echo $line; done
} < $file_out

